import type { Product } from "@/content/schemas";
import { validateProducts } from "@/content/validation";

const productFixtures = [
  {
    contentStatus: "approved",
    id: "almond-crunch",
    slug: "golden-crunch",
    category: "cookies",
    status: "active",
    name: "Golden Crunch",
    shortDescription: "A buttery cookie layered with sliced almonds, chocolate chips, and crisp cornflakes.",
    description:
      "Buttery cookies layered with premium sliced almonds, chocolate chips, and crispy cornflakes for a nutty, golden crunch in every bite. Available in normal or less-sugar sweetness.",
    images: [
      {
        src: "https://res.cloudinary.com/dodmwwp1w/image/upload/v1771084224/ChatGPT_Image_Feb_14_2026_10_48_13_PM_hnpjrt.png",
        alt: "Golden Crunch cookie with almonds and chocolate chips",
        width: 1200,
        height: 900,
      },
    ],
    flavorNotes: ["Buttery", "Nutty", "Crunchy"],
    texture: "Rich and crisp with a tender center",
    ingredients: [
      "Flour",
      "Eggs",
      "Australian Butter",
      "Brown Sugar",
      "Sliced Almonds",
      "Choco Chips",
      "Cornflakes",
    ],
    allergens: ["Gluten", "Eggs", "Milk", "Tree nuts"],
    shelfLife: "Best enjoyed within 3 months when stored in an airtight container",
    storage: "Store in a cool, dry place away from direct sunlight",
    deliveryNotes: "Same-day delivery is available for eligible areas; confirm availability, timing, and delivery fee via WhatsApp before checkout.",
    featured: false,
    variants: [
      {
        id: "golden-crunch-large",
        label: "Large 400gr",
        price: { amount: 220000, currency: "IDR" },
        sweetnessOptions: ["Normal", "Less sugar"],
        status: "active",
      },
      {
        id: "golden-crunch-medium",
        label: "Medium 150gr",
        price: { amount: 85000, currency: "IDR" },
        sweetnessOptions: ["Normal", "Less sugar"],
        status: "active",
      },
      {
        id: "golden-crunch-small",
        label: "Small 100gr",
        price: { amount: 65000, currency: "IDR" },
        sweetnessOptions: ["Normal", "Less sugar"],
        status: "active",
      },
      {
        id: "golden-crunch-mini",
        label: "Mini 30gr",
        price: { amount: 20000, currency: "IDR" },
        sweetnessOptions: ["Normal", "Less sugar"],
        status: "active",
      },
    ],
    seo: {
      title: "Golden Crunch | Tiny Bitty Cookies",
      description: "Discover Golden Crunch, a buttery cookie with sliced almonds, chocolate chips, and crisp cornflakes.",
    },
  },
  {
    contentStatus: "approved",
    id: "dark-crumbs",
    slug: "heavenly-bites",
    category: "cookies",
    status: "active",
    name: "Heavenly Bites",
    shortDescription: "A rich buttery cookie with dark cookie crumbs, chocolate chips, and choco cereal.",
    description:
      "Rich dark cookie crumbs, chocolate chips, and choco cereal folded into a buttery cookie for a crisp, cookies-and-cream inspired bite without naming the brand.",
    images: [
      {
        src: "https://res.cloudinary.com/dodmwwp1w/image/upload/v1771084221/ChatGPT_Image_Feb_14_2026_10_45_13_PM_qudpo4.png",
        alt: "Heavenly Bites cookie with dark crumbs and chocolate chips",
        width: 1200,
        height: 900,
      },
    ],
    flavorNotes: ["Chocolatey", "Buttery", "Crunchy"],
    texture: "Crisp and indulgent with a soft center",
    ingredients: [
      "Flour",
      "Eggs",
      "Australian Butter",
      "Brown Sugar",
      "Dark Crumbs",
      "Choco Chips",
      "Choco Cereal",
    ],
    allergens: ["Gluten", "Eggs", "Milk"],
    shelfLife: "Best enjoyed within 3 months when stored in an airtight container",
    storage: "Store in a cool, dry place away from direct sunlight",
    deliveryNotes: "Same-day delivery is available for eligible areas; confirm availability, timing, and delivery fee via WhatsApp before checkout.",
    featured: false,
    variants: [
      {
        id: "heavenly-bites-large",
        label: "Large 400gr",
        price: { amount: 220000, currency: "IDR" },
        status: "active",
      },
      {
        id: "heavenly-bites-medium",
        label: "Medium 150gr",
        price: { amount: 85000, currency: "IDR" },
        status: "active",
      },
      {
        id: "heavenly-bites-small",
        label: "Small 100gr",
        price: { amount: 65000, currency: "IDR" },
        status: "active",
      },
      {
        id: "heavenly-bites-mini",
        label: "Mini 30gr",
        price: { amount: 20000, currency: "IDR" },
        status: "active",
      },
    ],
    seo: {
      title: "Heavenly Bites | Tiny Bitty Cookies",
      description: "Try Heavenly Bites, a rich buttery cookie with dark cookie crumbs and chocolatey crunch.",
    },
  },
  {
    contentStatus: "approved",
    id: "oatmeal-raisin",
    slug: "harvest-haven",
    category: "cookies",
    status: "active",
    name: "Harvest Haven",
    shortDescription: "A comforting buttery cookie with raisins and oats for a chewy, fruity finish.",
    description:
      "Raisins and oats folded into a rich buttery cookie for a comforting mix of chewy fruit notes and crisp edges. Available in normal or less-sugar sweetness.",
    images: [
      {
        src: "https://res.cloudinary.com/dodmwwp1w/image/upload/v1771084222/ChatGPT_Image_Feb_14_2026_10_46_57_PM_khuilz.png",
        alt: "Harvest Haven cookie with raisins and oats",
        width: 1200,
        height: 900,
      },
    ],
    flavorNotes: ["Buttery", "Fruity", "Comforting"],
    texture: "Chewy edges with a tender bite",
    ingredients: ["Flour", "Eggs", "Australian Butter", "Brown Sugar", "Raisins", "Oats"],
    allergens: ["Gluten", "Eggs", "Milk"],
    shelfLife: "Best enjoyed within 3 months when stored in an airtight container",
    storage: "Store in a cool, dry place away from direct sunlight",
    deliveryNotes: "Same-day delivery is available for eligible areas; confirm availability, timing, and delivery fee via WhatsApp before checkout.",
    featured: false,
    variants: [
      {
        id: "harvest-haven-large",
        label: "Large 400gr",
        price: { amount: 220000, currency: "IDR" },
        sweetnessOptions: ["Normal", "Less sugar"],
        status: "active",
      },
      {
        id: "harvest-haven-medium",
        label: "Medium 150gr",
        price: { amount: 85000, currency: "IDR" },
        sweetnessOptions: ["Normal", "Less sugar"],
        status: "active",
      },
      {
        id: "harvest-haven-small",
        label: "Small 100gr",
        price: { amount: 65000, currency: "IDR" },
        sweetnessOptions: ["Normal", "Less sugar"],
        status: "active",
      },
      {
        id: "harvest-haven-mini",
        label: "Mini 30gr",
        price: { amount: 20000, currency: "IDR" },
        sweetnessOptions: ["Normal", "Less sugar"],
        status: "active",
      },
    ],
    seo: {
      title: "Harvest Haven | Tiny Bitty Cookies",
      description: "Discover Harvest Haven, a buttery cookie with raisins and oats for a comforting finish.",
    },
  },
  {
    contentStatus: "approved",
    id: "Desert-Crown",
    slug: "desert-crown-seasonal",
    category: "cookies",
    status: "active",
    name: "Desert Crown",
    shortDescription: "A luxurious seasonal cookie with roasted almonds, oats, and Medjool dates.",
    description:
      "The crown jewel of our collection, featuring a luxurious mix of roasted almonds, wholesome oats, and succulent Medjool dates for a sophisticated sweetness.",
    images: [
      {
        src: "https://res.cloudinary.com/dodmwwp1w/image/upload/v1771084221/ChatGPT_Image_Feb_14_2026_10_43_22_PM_kynlwe.png",
        alt: "Desert Crown cookie with almonds, oats, and dates",
        width: 1200,
        height: 900,
      },
    ],
    flavorNotes: ["Luxurious", "Nutty", "Sweet"],
    texture: "Tender and richly textured",
    ingredients: [
      "Flour",
      "Eggs",
      "Australian Butter",
      "Brown Sugar",
      "Roast Almonds",
      "Oats",
      "Medjool Dates",
    ],
    allergens: ["Gluten", "Eggs", "Milk", "Tree nuts"],
    shelfLife: "Best enjoyed within 3 months when stored in an airtight container",
    storage: "Store in a cool, dry place away from direct sunlight",
    deliveryNotes: "Same-day delivery is available for eligible areas; confirm availability, timing, and delivery fee via WhatsApp before checkout.",
    featured: true,
    variants: [
      {
        id: "desert-crown-large",
        label: "Large 400gr",
        price: { amount: 220000, currency: "IDR" },
        status: "active",
      },
      {
        id: "desert-crown-medium",
        label: "Medium 150gr",
        price: { amount: 85000, currency: "IDR" },
        status: "active",
      },
      {
        id: "desert-crown-small",
        label: "Small 100gr",
        price: { amount: 65000, currency: "IDR" },
        status: "active",
      },
      {
        id: "desert-crown-mini",
        label: "Mini 30gr",
        price: { amount: 20000, currency: "IDR" },
        status: "active",
      },
    ],
    seo: {
      title: "Desert Crown (seasonal) | Tiny Bitty Cookies",
      description: "Experience Desert Crown, a luxurious seasonal cookie with roasted almonds, oats, and Medjool dates.",
    },
  },
] satisfies Product[];

export const products = validateProducts(productFixtures);
